[package]
name = "pilou-bot"
version = "0.1.0"
edition = "2021"

[dependencies]

[dependencies.serenity]
default-features = false
features = ["client", "gateway", "model", "rustls_backend"]
version = "0.10.9"

[dependencies.tokio]
features = ["rt-multi-thread"]
version = "1.12.0"
